CREATE TABLE ACCOUNT (
    ACCOUNT_NO   VARCHAR2(20) PRIMARY KEY, -- 계좌번호
    USER_NAME    VARCHAR2(50) NOT NULL,    -- 소유주
    BALANCE      NUMBER(18, 2) DEFAULT 0,  -- 잔액
    UPDATE_DATE  TIMESTAMP DEFAULT SYSDATE -- 최종 수정일
);